name: Virtual Environment

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
  workflow_dispatch:
   
env:
  GitHubMail: ${{ secrets.GH_MAIL }}
  GitHubName: ${{ secrets.GH_USER }}
  Branch: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set git configs & secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Cleanup storage
        run: |
          chmod +x cleanup.sh
          ./cleanup.sh

      - name: Clone The Repository
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.REPO }} -b ${Branch} source

      - name: Settings up & installing requirements
        run: |
          cp config.env /source && cp token.pickle /source
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t bot
          docker image ls

      - name: Running mirror-bot
        timeout-minutes: 340
        continue-on-error: true
        run: |
          docker run --privileged --rm -i bot
          

      - name: Loop Workflow
        continue-on-error: true
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > loop.txt
          git add loop.txt
          git commit -m "Workflow : Loop"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
